"""Multi-shot Kling Omni call for the compute-world arrival arc.

Three shots × 3 sec = 9-second beat-block:
  18 — The Reveal:   slow dolly-in across the compute world, agent in awe
  19 — The Walk:     tracking with agent on glass walkway, brand-mark fragments
                     brightening as he passes
  20 — The Engine:   wide hero shot of the verification engine,
                     agent walks to lens edge, lens shines brilliantly

Output: assets/shadow_comic/transitions/multi_18_19_20.mp4

Audio is generated by Kling Omni per shot for placeholder; the user has
a `Cyan Proof.mp3` track to layer in during the final stitch.

Usage:
  REPLICATE_API_TOKEN=... python3 generate_multi_18_19_20.py
"""

from __future__ import annotations

import json
import logging
import os
import sys
from pathlib import Path

import replicate_helpers as base
import generate_shadow_comic as cb


ROOT = Path(__file__).parent.parent
TRANS_DIR = ROOT / "assets" / "clips"
OUT_PATH = TRANS_DIR / "multi_18_19_20.mp4"
LOG_PATH = TRANS_DIR / "generate_multi_18_19_20.log"
KLING_OMNI = "kwaivgi/kling-v3-omni-video"


def setup_logging() -> logging.Logger:
    TRANS_DIR.mkdir(parents=True, exist_ok=True)
    logger = logging.getLogger("multi_18_19_20")
    logger.setLevel(logging.INFO)
    if logger.handlers:
        return logger
    fmt = logging.Formatter("%(asctime)s %(levelname)s %(message)s")
    fh = logging.FileHandler(LOG_PATH, encoding="utf-8")
    fh.setFormatter(fmt)
    sh = logging.StreamHandler()
    sh.setFormatter(fmt)
    logger.addHandler(fh)
    logger.addHandler(sh)
    return logger


# Each shot prompt MUST stay under 512 chars (Kling multi_prompt cap).
# Common physics live in the top-level prompt.
COMMON_PHYSICS = (
    "Cinematic semi-photoreal CG, 1080p Pro, brand cyan exactly hex "
    "#24bce3 the only saturated color, otherwise deep cathedral-blacks, "
    "glass-greys, warm off-whites. The protagonist humanoid AI agent "
    "casts NO shadow on any surface in any of these shots. Other "
    "objects and architecture cast normal shadows. Static or smooth "
    "single camera per shot, no internal cuts. Reverent, awe-scale "
    "pacing. No on-screen text or UI."
)

SHOT_18 = (
    "Use <<<image_1>>>: slow dolly-in across a vast subterranean compute "
    "world — GPU towers blinking cyan, hanging model vaults turning "
    "luminous pages, transparent TEE glass chambers refracting cyan "
    "light, rivers of cyan light flowing between them. The agent stands "
    "motionless on a high mezzanine in foreground silhouette, dwarfed, "
    "casting no shadow. Audio: deep cathedral hum, harmonic resonance."
)

SHOT_19 = (
    "Use <<<image_2>>>: tracking with the agent walking a glass walkway "
    "through the compute world. The brand symbol (4-fold "
    "rotational mark, rounded petal-lobes around a center dot) is "
    "embedded in the floor and walls in cyan; each symbol GLOWS BRIGHTER "
    "as he passes, same shape just intensifying. Agent casts no shadow. "
    "Audio: soft footsteps, compute hum, chimes as fragments brighten."
)

SHOT_20 = (
    "Use <<<image_3>>>: colossal spherical verification engine like a "
    "captured star, with a lens shaped exactly like the [Your Brand] "
    "symbol pouring brilliant cyan light. The agent walks into frame "
    "and approaches the lens edge. The lens shines BRIGHTER as he "
    "nears, cyan beam intensifying, strong cyan rim-light hitting him. "
    "Clip ends with him at the lens edge silhouetted against the "
    "brilliant cyan aperture. Audio: deep engine hum, rising chord swell."
)


def main() -> int:
    logger = setup_logging()
    token = os.environ.get("REPLICATE_API_TOKEN")
    if not token:
        raise SystemExit("REPLICATE_API_TOKEN required.")
    import replicate

    client = replicate.Client(api_token=token)
    fields = base.schema_fields(client, KLING_OMNI, logger)

    p18 = next(p for p in cb.PANELS if p.idx == 18)
    p19 = next(p for p in cb.PANELS if p.idx == 19)
    p20 = next(p for p in cb.PANELS if p.idx == 20)
    for p in (p18, p19, p20):
        if not p.path.exists():
            raise SystemExit(f"Missing panel: {p.path.relative_to(ROOT)}")

    top_prompt = (
        "A three-shot beat-block of the compute-world arrival arc, each "
        "anchored to a specific reference image: shot 1 = <<<image_1>>>, "
        "shot 2 = <<<image_2>>>, shot 3 = <<<image_3>>>. The arc moves "
        "from awe-of-scale, to a tracking walk through the architecture "
        "of verification, to arrival at the central engine. " + COMMON_PHYSICS
    )

    multi_prompt = [
        {"prompt": SHOT_18, "duration": 3},
        {"prompt": SHOT_19, "duration": 3},
        {"prompt": SHOT_20, "duration": 3},
    ]
    for i, shot in enumerate(multi_prompt):
        if len(shot["prompt"]) >= 512:
            raise SystemExit(f"shot {i} prompt is {len(shot['prompt'])} chars (max 511)")

    payload: dict = {
        "prompt": top_prompt,
        "start_image": p18.path,
        "reference_images": [p18.path, p19.path, p20.path],
        "multi_prompt": json.dumps(multi_prompt),
        "mode": "pro",
        "generate_audio": True,
        "duration": 9,
    }
    payload = base.keep_supported_fields(payload, fields)

    logger.info("RUN multi-shot 18/19/20 -> %s", OUT_PATH.relative_to(ROOT))
    result = base.run_replicate(client, KLING_OMNI, payload, OUT_PATH, logger, dry_run=False, ROOT)
    if result["status"] != "ok":
        logger.error("FAIL: %s", result.get("error", "unknown"))
        return 1
    logger.info("OK %.1fMB", result["size_bytes"] / 1_000_000)
    return 0


if __name__ == "__main__":
    sys.exit(main())
